#!/usr/bin/env python3
"""Generate src/remote/assets/params.js from src/dsp/jp8000_params.h.

The Remote UI decodes the module's `temp` hex (the whole 528-byte temp
performance, as `state_get` emits it) in the browser, so it needs the same
address table the plugin compiles in: area, linear offset, 14-bit flag, range,
offset and sign. Those live in jp8000_params.h, which gen_params.py writes from
gearmulator's parameterDescriptions_je.json. This script reads the HEADER, not
the JSON, on purpose: the header is what the shipped dsp.so was built from, so
the page and the plugin can never disagree about where a byte lives -- and it
needs no submodule checkout to run.

Names, short names, enum option strings, units and defaults come from the
`jp_chain_params_prefix` JSON embedded in the same header.

    python3 src/tools/gen_remote_params.py
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HDR = os.path.join(ROOT, "src/dsp/jp8000_params.h")
OUT = os.path.join(ROOT, "src/remote/assets/params.js")

src = open(HDR).read()

# ---- address table ----------------------------------------------------------
# {"key", area, lin, bit14, vmin, vmax, off, def, nopts, neg},
ROW = re.compile(r'\{"([a-z0-9_]+)",\s*(\d+),\s*(0x[0-9a-f]+|\d+),\s*(\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(\d+),\s*(\d+)\}')
table = []
for m in ROW.finditer(src):
    key, area, lin, bit14, vmin, vmax, off, dflt, nopts, neg = m.groups()
    table.append(dict(key=key, area=int(area), lin=int(lin, 0), bit14=int(bit14) == 1,
                      min=int(vmin), max=int(vmax), off=int(off), default=int(dflt),
                      nopts=int(nopts), neg=int(neg) == 1))
count = int(re.search(r'#define JP_PARAM_COUNT (\d+)', src).group(1))
assert len(table) == count, "parsed %d rows, header declares %d" % (len(table), count)

# ---- embedded JSON strings ----------------------------------------------------
def c_string(name):
    """Concatenate the chunks of a `static const char name[] = "..." "...";`."""
    m = re.search(r'static const char %s\[\] =\s*((?:\s*"(?:[^"\\]|\\.)*")+)\s*;' % name, src)
    assert m, name
    out = []
    for chunk in re.finditer(r'"((?:[^"\\]|\\.)*)"', m.group(1)):
        out.append(chunk.group(1))
    s = "".join(out)
    # The header escapes only `"` and `\`.
    return s.replace('\\"', '"').replace("\\\\", "\\")

chain = json.loads(c_string("jp_chain_params_prefix") + "]")
hier = json.loads(c_string("jp_ui_hierarchy"))
meta = {p["key"]: p for p in chain}

# ---- merge ----------------------------------------------------------------------
params = []
for row in table:
    m = meta.get(row["key"], {})
    p = dict(key=row["key"], area=row["area"], lin=row["lin"], bit14=row["bit14"],
             min=row["min"], max=row["max"], off=row["off"], neg=row["neg"],
             default=m.get("default", row["default"]),
             name=m.get("name", row["key"]), short=m.get("short_name", ""))
    if row["nopts"]:
        opts = m.get("options")
        assert opts and len(opts) == row["nopts"], (row["key"], row["nopts"], opts)
        p["options"] = opts
    if "unit" in m: p["unit"] = m["unit"]
    if "viz" in m: p["viz"] = m["viz"]
    params.append(p)

# Plugin-side controls that are not sysex parameters but the page drives.
extra = [meta[k] for k in ("mode", "part", "buffer_ms") if k in meta]

# The system-area byte order `state_get` uses for "sys": one byte per exposed
# system parameter, in TABLE order. Recorded here so the decoder cannot drift.
sys_order = [p["key"] for p in params if p["area"] == 4]

out = {
    "generated_from": "src/dsp/jp8000_params.h",
    "areas": {"patch": 0, "part_up": 1, "part_lo": 2, "common": 3, "system": 4},
    # temp = common(36) partU(7) partL(7) patchU(239) patchL(239) = 528 bytes
    "temp_layout": [["common", 36], ["part_up", 7], ["part_lo", 7], ["patch_up", 239], ["patch_lo", 239]],
    "sys_order": sys_order,
    "params": params,
    "controls": extra,
    "hierarchy": hier,
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("/* GENERATED by src/tools/gen_remote_params.py from src/dsp/jp8000_params.h. DO NOT EDIT. */\n")
    f.write("window.JP8000 = ")
    json.dump(out, f, separators=(",", ":"), ensure_ascii=True)
    f.write(";\n")

by_area = {}
for p in params: by_area[p["area"]] = by_area.get(p["area"], 0) + 1
print("wrote %s: %d params %s, %d controls" % (os.path.relpath(OUT, ROOT), len(params), by_area, len(extra)))
